---
apiVersion: v1
kind: Service
metadata:
  namespace: k1-poc-dev
  name: api-gateway-app-prom
  labels:
    app: api-gateway-app-monitoring
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8081
      targetPort: http-metrics
  selector:
    app: api-gateway-app
