apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-api-gateway
  namespace: k1-poc-dev
data:
  promtail.yaml: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
        log_level: "debug"
      positions:
        filename: /tmp/positions.yaml
      clients: # Specify target
         - url: http://loki-write.monitoring.svc.cluster.local:3100/loki/api/v1/push
      scrape_configs:
        - job_name:  "logs_k1_poc_dev" 
          static_configs: 
            - targets: 
                - localhost 
              labels:
                app: "logs_k1_poc_dev"
                environment: "k1-poc-dev" 
                __path__: /app/logs/log_k1_dev.log # Any file .log in the EmptyDir Volume.
