apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: k1-poc-dev
spec:
  type:  ClusterIP
  selector:
    app: api-gateway-app
  ports:
    - name: http
      port: 80
      targetPort: http
